# Generated by Django 4.2.1 on 2024-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['id'], 'verbose_name': 'Игры', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, verbose_name='URL'),
        ),
    ]
