# Generated by Django 4.2.1 on 2024-04-21 07:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='is_verify',
            field=models.BooleanField(choices=[(0, 'На проверке'), (1, 'Проверено')], default=1),
        ),
    ]
