# Generated by Django 4.2.1 on 2024-04-26 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_genre_studio_alter_game_managers_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.studio'),
        ),
    ]
