# Generated by Django 4.2.1 on 2024-05-03 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0008_game_poster_alter_game_genre_alter_game_is_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_verify',
            field=models.BooleanField(choices=[(False, 'На проверке'), (True, 'Одобрено')], default=0, verbose_name='Статус'),
        ),
    ]
