# Generated by Django 4.2.1 on 2024-05-03 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0009_game_editor_alter_game_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='user_score',
            field=models.ManyToManyField(blank=True, default=True, null=True, related_name='user_score', to=settings.AUTH_USER_MODEL, verbose_name='Оценка пользователя'),
        ),
    ]
