# Generated by Django 4.2.1 on 2024-05-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0010_game_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user_score',
        ),
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True, verbose_name='Оценка')),
                ('review', models.TextField(null=True, verbose_name='Отзыв')),
                ('game', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='game.game')),
                ('user', models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
                'ordering': ['rating'],
            },
        ),
    ]
