# Generated by Django 4.2.1 on 2024-05-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_game_user_score_gameuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='review',
            field=models.TextField(default='', verbose_name='Отзыв'),
        ),
    ]
